# This is the configuration used to check the rubocop source code.

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'spec/spec_helper.rb'
    - 'Gemfile'
    - 'Rakefile'
    - 'bin/*'

Lint/MissingSuper:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Layout/LineLength:
  Max: 120

Style/SymbolArray:
  Exclude:
    - 'Gemfile'

Style/Documentation:
  Enabled: false

Style/RescueStandardError:
  EnforcedStyle: implicit