version: "3.7"

networks:
  shared_app_services:
    external: true
volumes:
  bundler_gems:

services:
  app: &app
    build:
      context: .
    volumes:
      - .:/app
      - bundler_gems:/usr/local/bundle/
    external_links:
      - pubsub
    networks: # required to connect to pubsub
      - shared_app_services

  listener:
    <<: *app
    command: bash -c "DB_POOL=20 bundle install && rails db:migrate && bundle exec rake pub_sub_model_sync:start"
