name: Create release from tag
on:
  push:
    tags: # Create a release once a git tag is published
      - '*'

jobs:
  release-builder:
    uses: owen2345/reusable-ci-cd-actions/.github/workflows/release_builder_from_tag.yml@main
    with:
      commit_mode: true # If true, then fetches all commit titles from all changes. If false, then fetches only the PR titles from all changes.